name: PR + GitHub Actions

on:
  push:
    branches:
      - feature/test1

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract Git Commit Data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > COMMIT_AUTHOR

      - name: Create Pull Request
        id: autopr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: develop
          base: feature/test1
          title: "Pull Request With GitHub Actions"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}">
          body:
            Automatic Creation Of Pull Request
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.autopr.outputs.pull-request-number }}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.autopr.outputs.pull-request-number }}
          method: merge
