name: Git Flow Workflow

on:
  push:
    branches:
      - feature/test1

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "juancondorijara"
          git config user.email "juan.condori.jara@vallegrande.edu.pe"
          
      - name: Merge to develop
        run: |
          git flow feature finish test1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
