name: Git Flow Workflow

on:
  push:
    branches:
      - feature/test1

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Merge by labeled
        uses: devmasx/merge-branch@master
        with:
          label_name: 'merged in develop'
          message: Merge staging into develop
          target_branch: develop
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

